### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by yuya-okada527** [yuya-okada527/k8s-app-sample#1]
## Overview
Initialize project.

## Tasks
- [x] Start SpringBoot CLI Application Project
- [x] Containerize CLI app
- [x] Add template file for CloudFormation
  - [x] network template
  - [x] S3 template
- [x] Create S3 bucket
- [x] Add connection to S3 bucket

**Comment by yuya-okada527** [comment]
finish this issue
