### ISSUE TITLE
Setup Kubernetes

### ISSUE THREAD

**Issue by yuya-okada527** [yuya-okada527/k8s-app-sample#2]
## Overview
Setup Kubernetes application.

## Tasks
- [ ] Add CloudFormation template file for EKS
  - [ ] Start `eksctl create cluster`
  - [ ] Understand CloudFormation template crated by eksctl
  - [ ] Make CloudFormation template file
    - [ ] EKS cluster template
    - [ ] EKS nodegroup template
- [ ] Add manifest file for Kubernetes
  - [ ] manifest for Secret
  - [ ] manifest for CronJob
- [ ] Start EKS project
